language: python
#dist: xenial
#sudo: required
python:
  - "2.6"
  - "2.7"
    #  - "3.3"
  - "3.4"
    #  - "3.5"
    #  - "3.6"
    #  - "3.7"
services:
      - couchdb
# command to install dependencies
before_install:
    #    - sudo rm /opt/pyenv/shims/python*
    #- sudo rm /usr/bin/python*
    - sudo apt-get update
    - sudo apt-get install libdpm-dev libboost-all-dev python-dev python3-dev libglibmm-2.4-1c2a 
    - sudo apt-get install -y dpkg
    - wget http://mirrors.kernel.org/ubuntu/pool/main/j/json-c/libjson-c3_0.12.1-1.3_amd64.deb
    - wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gfal2/libgfal-transfer2_2.15.2-1_amd64.deb
    - wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gfal2/gfal2_2.15.2-1_all.deb
    - wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gfal2/libgfal2-2_2.15.2-1_amd64.deb
    - wget http://mirrors.kernel.org/ubuntu/pool/main/a/attr/libattr1_2.4.47-2build1_amd64.deb
    - wget http://mirrors.kernel.org/ubuntu/pool/main/a/attr/libattr1-dev_2.4.47-2build1_amd64.deb
    - wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gfal2/libgfal2-dev_2.15.2-1_amd64.deb  
    - wget http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb
    - wget http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/gcc-5-base_5.4.0-6ubuntu1~16.04.10_amd64.deb
    - sudo dpkg --install gcc-5-base_5.4.0-6ubuntu1~16.04.10_amd64.deb
    - sudo dpkg --install libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb
    - sudo dpkg --install libjson-c3_0.12.1-1.3_amd64.deb 
    - sudo dpkg --install libgfal2-2_2.15.2-1_amd64.deb
    - sudo dpkg --install libgfal-transfer2_2.15.2-1_amd64.deb
    - sudo dpkg --install gfal2_2.15.2-1_all.deb
    - sudo dpkg --install libattr1_2.4.47-2build1_amd64.deb 
    - sudo dpkg --install libattr1-dev_2.4.47-2build1_amd64.deb 
    - sudo dpkg --install libgfal2-dev_2.15.2-1_amd64.deb
      #    - sudo find / -name "libboost_python*"
      #    - echo ${Boost_PYTHON_3_SUFFIX}
    - ls $(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
    - export PYTHON_INCLUDE_DIR=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
    - export PYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))")/libpython*[!m].so
      #    - pip install  --verbose git+https://github.com/cern-fts/gfal2-python.git
    - pip install --verbose git+https://gitlab.cern.ch/dmc/gfal2-binding
    - which -a python 
      #    - sudo apt-get install globus-gass-copy-progs voms-clients -y
      #    - sudo add-apt-repository -y 'deb http://repository.egi.eu/sw/production/cas/1/current egi-igtf core' 
      #    - sudo apt-get update 
      #    - sudo mkdir -p /etc/grid-security/certificates/
      #    - sudo apt-get -y --allow-unauthenticated install ca-policy-egi-core 
    - pip install mock
      #    - wget http://www.globus.org/ftppub/gt6/installers/repo/globus-toolkit-repo_latest_all.deb
      #    - dpkg -i globus-toolkit-repo_latest_all.deb
      #    - apt-get install globus-data-management-client
    - pip install codecov
    - curl -X PUT localhost:5984/test_db

script:
    - nosetests --with-coverage

after_success:
  - codecov

# # command to run tests
